INSERT INTO users VALUES('dummy1@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy2@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy3@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy4@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy5@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy6@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy7@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy8@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy9@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy10@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy11@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy12@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy13@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');
INSERT INTO users VALUES('dummy14@gmail.com','DummyUser','$2b$10$hj0GjGnK7TcAJzAIwEcXpuLvBmHzZHPZ1Y3YdHf6Ha0JNglJKmx/2');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy1@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy2@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy3@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy4@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy5@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy6@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy7@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy8@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy9@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy10@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy11@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy12@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy13@gmail.com', 'Board 11', 'bg_default');

INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 1', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 2', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 3', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 4', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 5', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 6', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 7', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 8', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 9', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 10', 'bg_default');
INSERT INTO boards(user_id, title, bg_id) VALUES('dummy14@gmail.com', 'Board 11', 'bg_default');